# The project name is mandatory
name: "daily"
# Optionally you can provide a project version
version: "1.0"
# Optionally you can provide a description
description: "
    This is a simple but very comprehensive example project for Flowman 
  "

# The following modules simply contain a list of subdirectories containing YAML files containing all entities
modules:
  # All relations describing data sources and sinks are stored in the "model" subdirectory 
  - model
  # Data transformations (mappings) are stored in the "mapping" subdirectory
  - mapping
  # Build targets go into the "target" directory
  - target
  # Build jobs bundling multiple targets go into the "job" directory
  - job
  # All configurations go into the "config" directory
  - config

  - test