jobs:
  # Define the 'main' job, which implicitly is used whenever you build the whole project
  main:
    parameters:
      name: year
      type: Integer
      default: 2014
    # List all targets which should be built as part of the `main` job
    targets:
      - data_target